sign_name_dict = {0:'Speed limit (20km/h)',
        1:'Speed limit (30km/h)',
        2:'Speed limit (50km/h)',
        3:'Speed limit (60km/h)',
        4:'Speed limit (70km/h)',
        5:'Speed limit (80km/h)',
        6:'End of speed limit (80km/h)',
        7:'Speed limit (100km/h)',
        8:'Speed limit (120km/h)',
        9:'No passing',
        10:'No passing for vehicles over 3.5 metric tons',
        11:'Right-of-way at the next intersection',
        12:'Priority road',
        13:'Yield',
        14:'Stop',
        15:'No vehicles',
        16:'Vehicles over 3.5 metric tons prohibited',
        17:'No entry',
        18:'General caution',
        19:'Dangerous curve to the left',
        20:'Dangerous curve to the right',
        21:'Double curve',
        22:'Bumpy road',
        23:'Slippery road',
        24:'Road narrows on the right',
        25:'Road work',
        26:'Traffic signals',
        27:'Pedestrians',
        28:'Children crossing',
        29:'Bicycles crossing',
        30:'Beware of ice/snow',
        31:'Wild animals crossing',
        32:'End of all speed and passing limits',
        33:'Turn right ahead',
        34:'Turn left ahead',
        35:'Ahead only',
        36:'Go straight or right',
        37:'Go straight or left',
        38:'Keep right',
        39:'Keep left',
        40:'Roundabout mandatory',
        41:'End of no passing',
        42:'End of no passing by vehicles over 3.5 metric tons'}

        
sign_name_dict_short = {0:'Speed limit (20km/h)',
        1:'Speed limit\n(30km/h)',
        2:'Speed limit\n(50km/h)',
        3:'Speed limit\n(60km/h)',
        4:'Speed limit\n(70km/h)',
        5:'Speed limit\n(80km/h)',
        6:'End of speed\nlimit (80km/h)',
        7:'Speed limit\n(100km/h)',
        8:'Speed limit\n(120km/h)',
        9:'No passing',
        10:'No passing for\nvehicles over\n3.5 metric tons',
        11:'Right-of-way\nat the next\nintersection',
        12:'Priority road',
        13:'Yield',
        14:'Stop',
        15:'No vehicles',
        16:'Vehicles over\n3.5 metric tons prohibited',
        17:'No entry',
        18:'General caution',
        19:'Dangerous curve\nto the left',
        20:'Dangerous curve\nto the right',
        21:'Double curve',
        22:'Bumpy road',
        23:'Slippery road',
        24:'Road narrows\non the right',
        25:'Road work',
        26:'Traffic signals',
        27:'Pedestrians',
        28:'Children\ncrossing',
        29:'Bicycles\ncrossing',
        30:'Beware of\nice/snow',
        31:'Wild animals\ncrossing',
        32:'End of all speed\nand passing limits',
        33:'Turn right\nahead',
        34:'Turn left\nahead',
        35:'Ahead only',
        36:'Go straight\nor right',
        37:'Go straight\nor left',
        38:'Keep right',
        39:'Keep left',
        40:'Roundabout\nmandatory',
        41:'End of\nno passing',
        42:'End of\nno passing by\nvehicles over\n3.5 metric tons'}
